In [173]:
# csvファイルの読み込み
import pandas as pd
data = pd.read_csv('../data/clean/clean_NVDA_data.csv')

In [174]:
data.head()

         Date     Close      High       Low      Open     Volume
0  2020-01-03  5.876163  5.919972  5.827126  5.852018  205384000
1  2020-01-06  5.900806  5.906033  5.756684  5.782820  262636000
2  2020-01-07  5.972244  6.018045  5.884128  5.929182  314856000
3  2020-01-08  5.983445  6.024765  5.927937  5.968012  277108000
4  2020-01-09  6.049160  6.121595  5.995394  6.069820  255112000

In [175]:
data.dtypes

Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [169]:
# データの型を確認
data.dtypes

Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [170]:
def clean_stock_data(data):

    """株価データをクリーンアップする"""
    raw_data = data.copy()

    # 日付をdatetime型に変換
    raw_data['Date'] = pd.to_datetime(raw_data['Date'], errors='coerce')

    return raw_data

data = clean_stock_data(data)
data.head()

        Date     Close      High       Low      Open     Volume
0 2020-01-03  5.876163  5.919973  5.827127  5.852019  205384000
1 2020-01-06  5.900805  5.906032  5.756683  5.782819  262636000
2 2020-01-07  5.972246  6.018046  5.884129  5.929183  314856000
3 2020-01-08  5.983447  6.024767  5.927938  5.968014  277108000
4 2020-01-09  6.049160  6.121595  5.995394  6.069820  255112000

In [171]:
data.dtypes

Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

In [172]:
data.select_dtypes(include='object').columns

Index([], dtype='object')

In [140]:
data.isna().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [141]:
cols = ['Close', 'High', 'Low', 'Open', 'Volume']

for col in cols:
    # 数値に変換できない値（＝NaNになったもの）を探す
    bad_values = data[pd.to_numeric(data[col], errors='coerce').isna()][col].unique()
    
    print(f"{col} の中で数値に変換できなかった値: {bad_values}")

Close の中で数値に変換できなかった値: []
High の中で数値に変換できなかった値: []
Low の中で数値に変換できなかった値: []
Open の中で数値に変換できなかった値: []
Volume の中で数値に変換できなかった値: []

In [142]:
def clean_stock_data(data):
    data = data.iloc[1:].reset_index(drop=True)
    data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

    cols = ['Close', 'High', 'Low', 'Open', 'Volume']
    for col in cols:
        data[col] = pd.to_numeric(data[col], errors='coerce')

    return data

# 呼び出し
data = clean_stock_data(data)

# 型を確認
print(data.dtypes)

Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

In [143]:
print(data.dtypes)

Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

In [144]:
# これをやった？
cols = ['Close', 'High', 'Low', 'Open', 'Volume']
for col in cols:
    data[col] = pd.to_numeric(data[col], errors='coerce')

In [145]:
data.dtypes

Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object